arm_group:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_search_resolution: 0.0050000000000000001
  kinematics_solver_timeout: 0.0050000000000000001
# gripper_group does not need a kinematics solver as it's not a kinematic chain
# It only contains two independent joints (JointGL and JointGR)