# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - arm_group_controller
    - gripper_group_controller

  arm_group_controller:
    type: FollowJointTrajectory
    action_ns: arm_group_controller/follow_joint_trajectory
    default: true
    joints:
      - Joint1
      - Joint2
      - Joint3
      - Joint4
  gripper_group_controller:
    type: FollowJointTrajectory
    action_ns: gripper_group_controller/follow_joint_trajectory
    default: false
    joints:
      - JointGL
      - JointGR